### ISSUE TITLE
Can't save a word without a context sentence

### ISSUE THREAD

**Issue by djrenren** [teamdotjs/v2#193]
This is no bueno. We should be saving word infos without context sentences.

**Comment by mwitte98** [comment]
@djrenren is this happening in lesson update? A `Wordinfo` doesn't have to have a `Sentence` when being updated, but it does have to have one for practice generation. The only attribute a `Sentence` has is `context_sentence` so it has to be required or we'll have not unique rows in the db

**Comment by djrenren** [comment]
Ummm I was experiencing this issue when I attempted to edit one of the seeded lessons in the front end.

**Comment by mwitte98** [comment]
@djrenren Do you have any practices generated for that lesson? If so, you can't edit any words. Can you push what you're working on to a branch for me to look at it?

**Comment by djrenren** [comment]
it was an issue on my end where the practices existed but weren't showing up. My b.
