### ISSUE TITLE
Word editor not disabling/enabling until another word clicked

### ISSUE THREAD

**Issue by mwitte98** [teamdotjs/v2#215]
When a word is selected in the word editor and you generate that lesson's first practice, the word editor is not disabled until another word is selected, but "You cannot edit words while practices exist" does appear as expected.

Also when you delete a lesson's only practice and a word is selected, that word in the word editor is not enabled until another work is selected, but "You cannot edit words while practices exist" does disappear as expected.

**Comment by djrenren** [comment]
ah that's probably a problem with shouldComponentUpdate. On it.
