### ISSUE TITLE
Question generation performance

### ISSUE THREAD

**Issue by mwitte98** [teamdotjs/v2#230]

**Comment by mwitte98** [comment]
@teamdotjs/maintainers I set up code profiling locally and about 92% of the time generating questions is spent loading and saving data. The data is already as small as it can be so there's nothing that can be changed that would make any difference. I believe the crash on Thursday has to do with load on Heroku, likely because of writing to the logs.

**Comment by djrenren** [comment]
That's cuz we make a million roundtrips due to ActiveRecord lazy loading. We can fix this even if it requires a manual query.

**Comment by mwitte98** [comment]
We might be able to just do eager loading and not have to do manual queries, but I'll look into that more

**Comment by djrenren** [comment]
Yeah we'll need to be sure to scope it to just the fields we care about though in order to cut down the memory load
