### ISSUE TITLE
500's when patching lessons

### ISSUE THREAD

**Issue by 7imbrook** [teamdotjs/v2#93]
Getting nil class errors, can't update anything.

**Comment by mwitte98** [comment]
@7imbrook Can I see the format of the object you're including in the patch request?

**Comment by 7imbrook** [comment]
``` json
{
  "id": 1,
  "title": "Untitled",
  "wordinfos": []
}
```

It's the same as what I'm getting back from a fetch.

**Comment by mwitte98** [comment]
```
{
  "lesson": {
    "id": 1,
    "title": "Untitled",
    "wordinfos": []
  }
}
```

The lesson object needs to be a value to the `"lesson"` key because of strong parameters. It's the same as what we're doing for lesson create and user create.

**Comment by 7imbrook** [comment]
@mwitte98 why does strong parameters require this? the PATCH to /api/lesson/:id... should cover that. IMO

**Comment by 7imbrook** [comment]
@mwitte98 also did not resolve the issue

**Comment by 7imbrook** [comment]
Ah I see that word_info is now wordinfo

**Comment by mwitte98** [comment]
We don't have to use require, but it's standard to. If we don't want to require here then we shouldn't anywhere in the project for consistency.
