### ISSUE TITLE
Word infos on lessons should update if a word is taken, not 400.

### ISSUE THREAD

**Issue by 7imbrook** [teamdotjs/v2#95]
if I send 

```json
{
    "word": "test"
}
```

again, it just just 'update' it, aka do nothing

**Comment by 7imbrook** [comment]
It would be great to just ignore blank words instead of erroring, I'm filtering now, but the backend should try a 'best effort' to not error.

**Comment by mwitte98** [comment]
If a word is already in the lesson, `id` needs to be included or it will try to create that word. We said before that we don't want to have duplicate words in a lesson so that should be an error

**Comment by 7imbrook** [comment]
Hmm I thought I was sending the id along with it. Let me check

**Comment by 7imbrook** [comment]
I am sending ids

**Comment by mwitte98** [comment]
It's case insensitive so you can't have Test and test in the same lesson
